require_relative "simplepage"
require_relative "user"
require_relative "home"
require_relative "question"
require_relative "draft"
require_relative "vote"
require_relative "comment"
require_relative "profile"
require_relative "message"
require_relative "watchlist"
require_relative "tag"
require_relative "sns"
require_relative "captcha"
require_relative "search"
require_relative "report"
require_relative "feedback"

require_relative "admin/init"
